FROM python:3.10.9-slim AS build

RUN mkdir /app
COPY requirements.txt /app
WORKDIR /app
RUN pip3 install -r /app/requirements.txt --no-cache-dir
COPY tender_service/ /app
WORKDIR /app

EXPOSE 8080

ENV SERVER_ADDRESS=SERVER_ADDRESS
ENV POSTGRES_CONN=POSTGRES_CONN
ENV POSTGRES_JDBC_URL=POSTGRES_JDBC_URL
ENV POSTGRES_USERNAME=POSTGRES_USERNAME
ENV POSTGRES_PASSWORD=POSTGRES_PASSWORD 
ENV POSTGRES_HOST=POSTGRES_HOST 
ENV POSTGRES_PORT=POSTGRES_PORT
ENV POSTGRES_DATABASE=POSTGRES_DATABASE 

ENTRYPOINT python3 manage.py migrate ; python3 manage.py runserver 0:8080
