# Generated by Django 5.1.1 on 2024-09-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='author_feedback',
            field=models.ForeignKey(default='550e8400-e29b-41d4-a716-446655440002', on_delete=django.db.models.deletion.CASCADE, related_name='review_author_feedback', to='tenders.employee'),
            preserve_default=False,
        ),
    ]
