# Generated by Django 5.1.1 on 2024-09-13 11:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_rename_author_review_user_review_author_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='approved_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='bid',
            name='quorum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
